-- MySQL Script generated by MySQL Workbench
-- Thu Dec  6 11:20:36 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema footballtyper
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `footballtyper` ;

-- -----------------------------------------------------
-- Schema footballtyper
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `footballtyper` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `footballtyper` ;

-- -----------------------------------------------------
-- Table `bet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bet` ;

CREATE TABLE IF NOT EXISTS `bet` (
  `bet_id` INT(11) NOT NULL AUTO_INCREMENT,
  `team_home_goals` INT(11) NULL DEFAULT '0',
  `team_away_goals` INT(11) NULL DEFAULT '0',
  `membership_id` INT(11) NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `match_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`bet_id`),
  CONSTRAINT `fk_match_bet`
    FOREIGN KEY (`match_id`)
    REFERENCES `match` (`match_id`),
  CONSTRAINT `fk_membership_bet`
    FOREIGN KEY (`membership_id`)
    REFERENCES `membership` (`memebership_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_membership_bet_idx` ON `bet` (`membership_id` ASC) VISIBLE;

CREATE INDEX `fk_match_bet_idx` ON `bet` (`match_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `league`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `league` ;

CREATE TABLE IF NOT EXISTS `league` (
  `league_id` INT(11) NOT NULL AUTO_INCREMENT,
  `league_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`league_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `league_name_UNIQUE` ON `league` (`league_name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `match`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `match` ;

CREATE TABLE IF NOT EXISTS `match` (
  `match_id` INT(11) NOT NULL AUTO_INCREMENT,
  `team_home` VARCHAR(45) NOT NULL,
  `team_away` VARCHAR(45) NOT NULL,
  `team_home_goals` INT(11) NULL DEFAULT NULL,
  `team_away_goals` INT(11) NULL DEFAULT NULL,
  `match_date` DATE NULL DEFAULT NULL,
  `queue_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`match_id`),
  CONSTRAINT `fk_queue_match`
    FOREIGN KEY (`queue_id`)
    REFERENCES `queue` (`queue_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_queue_match_idx` ON `match` (`queue_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `membership`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `membership` ;

CREATE TABLE IF NOT EXISTS `membership` (
  `memebership_id` INT(11) NOT NULL AUTO_INCREMENT,
  `league_id` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  `points` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`memebership_id`),
  CONSTRAINT `fk_liga_membership`
    FOREIGN KEY (`league_id`)
    REFERENCES `league` (`league_id`),
  CONSTRAINT `fk_user_membership`
    FOREIGN KEY (`user_id`)
    REFERENCES `user_table` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_liga_membership_idx` ON `membership` (`league_id` ASC) VISIBLE;

CREATE INDEX `fk_user_membership_idx` ON `membership` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `queue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `queue` ;

CREATE TABLE IF NOT EXISTS `queue` (
  `queue_id` INT(11) NOT NULL AUTO_INCREMENT,
  `league_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`queue_id`),
  CONSTRAINT `fk_league_queue`
    FOREIGN KEY (`league_id`)
    REFERENCES `league` (`league_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_league_queue_idx` ON `queue` (`league_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `user_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_table` ;

CREATE TABLE IF NOT EXISTS `user_table` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `login_UNIQUE` ON `user_table` (`login` ASC) VISIBLE;

CREATE UNIQUE INDEX `email_UNIQUE` ON `user_table` (`email` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
